name: Rinon Ninqueon
title: Rinon Ninqueon Electronics
email: mail@rinonninqueon.ru
description: "Заметки по электронике и музыке и переводы."
baseurl: ""
url: "http://rinonninqueon.ru"

destination: ./
markdown: kramdown
kramdown:
 input: GFM
 hard_wrap: false
 extensions: ["strikethrough", "smart"]
permalink: /:categories/:title/
pagination: 15
paginate_path: "/page:num"
highlighter: rouge
encoding: utf-8