name: Rínon Nínqueon
title: Rínon Nínqueon
email: mail@rinonninqueon.ru
description: "Заметки по электронике, музыке и переводы"
baseurl: ""
url: "http://rinonninqueon.ru"

destination: ./
markdown: kramdown
kramdown:
 input: GFM
 hard_wrap: false
 extensions: ["strikethrough", "smart"]
permalink: /:categories/:title/
str_next_page: "Туда"  
str_previous_page: "Сюда"
pagination_nr: 5
pagination: 15
paginate_path: "/page:num"
highlighter: rouge
encoding: utf-8